### ISSUE TITLE
idrac command processing failed 

### ISSUE THREAD

**Issue by kanapuliAthavan** [dell/Dell-EMC-Ansible-Modules-for-iDRAC#1]
I am trying to change the SNMP community name using dellemc_configure_idrac_services module and my playbook is as follows 

```
**Play file**
---

- hosts: all
  gather_facts: False
  become: yes
  become_method: sudo
  user: root
  roles:
    - snmp-configure

**snmp-configure role main.yml**
---
- name: setup idrac community name
  dellemc_configure_idrac_services:
      idrac_ip: "xxx.xxx.xx.xx"
      idrac_user: "root"
      idrac_pwd: "xxxxx"
      share_name: "xxx.xxx.xx.xx/nfsfileshare"
      snmp_enable: "Enabled"
      community_name: "my_new-name"
  become: yes
```

When I try to run this play , I always get the following error as Command Processing Failed,

```
"module_stdout": "\rcmdstat\r\n\r\tstatus       : 2\r\n\r\tstatus_tag   : COMMAND PROCESSING FAILED\r\n\r\terror        : 252\r\n\r\terror_tag    : COMMAND SYNTAX ERROR\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0

```

What could be the actual problem here?
