### ISSUE TITLE
Use all the free disk space for new virtual disk

### ISSUE THREAD

**Issue by jjeganathan** [dell/Dell-EMC-Ansible-Modules-for-iDRAC#19]
Hello,

I'm trying to create two virtual disks with 7 disks, each VD on RAID 6.
The first one with 128Gb and the second with all the remaining disk space.

I can create the first VD without problem but I cannot find a way to create the second VD with left space.
I know this is possible on the GUI by leaving a blank box in "Capacity"

Thanks !

**Comment by anupamaloke** [comment]
@jjeganathan , could you please share the playbook with us?

**Comment by jjeganathan** [comment]
Sure.
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Create multiple volume.
    dellemc_idrac_storage_volume:
        idrac_ip: xxxxxx
        idrac_user: root
        idrac_pwd: xxxxxx
        raid_reset_config: "True"
        state: "create"
        controller_id: "RAID.Integrated.1-1"
        number_dedicated_hot_spare: 1
        volumes:
          - name: "System"
            drives:
              id: ["Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.2:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.3:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.4:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.5:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.6:Enclosure.Internal.0-1:RAID.Integrated.1-1"]
            span_length: 7
            volume_type: "RAID 6"
            capacity: "128"
          - name: "Data"
            span_length: 7
            drives:
              id: ["Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.2:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.3:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.4:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.5:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                   "Disk.Bay.6:Enclosure.Internal.0-1:RAID.Integrated.1-1"]
            volume_type: "RAID 6"
```

Moreover, I have "Disk.Bay.7:Enclosure.Internal.0-1:RAID.Integrated.1-1" and I want it to be a Global hotspare. How should I proceed ?

Thanks ! :)
